package com.dxc.bankia.traffic_postfilter_rules.sanction;

rule "Driver with 10 or more points a notification"
    when
        $d: Driver()
        Number(intValue >= 10) from accumulate(
            Santion(
                $p: points
            ) from collect(Sanction(driver == $d)),
            init(int count = 0;),
            action(count += $p;),
            reverse(count -= $p;),
            result(count)
        )
    then
        Notification fact0 = new Notification();
//		fact0.setEventId( $e.getId() );
//		fact0.setEventType( $t );
		fact0.setType( Notification.Type.NOT_COMPLIANCE );
		fact0.setMessage( "driver "+$d.identificationNumber+" spent 10 point already . Total points"+intValue);
		insert( fact0 );    

end


rule "Driver 2 with 10 or more points a notification"
when
    $d: Driver()
    Number( intValue > 10 ) from accumulate (
        Sanction ( driver = $d , $points: points),
        sum($points)
    )
then
        Notification fact0 = new Notification();
//		fact0.setEventId( $e.getId() );
//		fact0.setEventType( $t );
		fact0.setType( Notification.Type.NOT_COMPLIANCE );
		fact0.setMessage( "driver "+$d.identificationNumber+" spent 10 point already . Total points"+intValue);
		insert( fact0 );   
end

