package com.dxc.bankia.traffic_postfilter_rules.itv;


package com.dxc.bankia.traffic_postfilter_rules.itv;

import com.dxc.bankia.model.Event;
import com.dxc.bankia.model.Vehicle;
import com.dxc.bankia.model.Notification;
import com.dxc.bankia.model.functions.DateUtils;

rule "itv set date"
	when
		$e : Event( $t : type == ( Event.Type.REQUEST_CAR_ITV_COMPLIANCE ) , vehicle != null )
		$v : Vehicle(nextItvDate == null) from $e.getVehicle()
     then
      insert($v);
end
