package com.dxc.bankia.traffic_postfilter_rules.itv;
import com.dxc.bankia.model.Vehicle;
import com.dxc.bankia.model.functions.DateUtils;

rule "itv_period_4"
	when
		$vehicle : Vehicle( age >= 10 , age < 100 , country == Country.ES , category == Vehicle.Category.BIKE , nextItvDate == null )
	then
		modify($vehicle) {
		$vehicle.setNextItvDate(DateUtils.addYears($vehicle.getBaseDateToCalculateNextItvDate(),1))
		}
end